export const debitAccounts = [
    { code: '4010', name: "Xaridorlar va buyurtmachilar qarzi" },
    { code: '4110', name: "Shu‘ba va qaram korxonalar bilan hisob-kitoblar" },
    { code: '4120', name: "Shu‘ba va qaram korxonalar bilan hisob-kitoblar" },
    { code: '4220', name: "Xizmat safari uchun bo‘naklar" },
    { code: '4230', name: "Umumxo‘jalik xarajatlari uchun bo‘naklar" },
    { code: '4310', name: "Yetkazib beruvchilarga berilgan bo‘naklar" },
    { code: '4610', name: "Ta’sischilar qarzi (ustav kapitali)" },
    { code: '4710', name: "Xodimlar kreditga tovarlar uchun qarzi" },
    { code: '4720', name: "Xodimlarga berilgan ssudalar (qarzlar)" },
    { code: '4730', name: "Aybdor shaxslardan kamomadlar va zararlar" },
    { code: '4790', name: "Mehnatga ortiqcha to‘langan summalar" },
    { code: '4810', name: "Moliyaviy ijara bo‘yicha qarzlar" },
    { code: '4830', name: "Boshqa korxonalardagi ulushdan daromadlar" },
    { code: '5010', name: "Milliy valutadagi pul mablag’lari" },
    { code: '5110', name: "Hisob-kitob schyoti (milliy valyutada)" },
    { code: '5210', name: "Valyuta hisob-kitob schyoti" },
    { code: '5530', name: "Bankdagi maxsus schyotlar" },
    { code: '5710', name: "Yo‘lda pul mablag‘lari (inkasso)" },
    { code: '5910', name: "Vaqtinchalik kamomadlar hisobi" },
    { code: '6010', name: "Yetkazib beruvchilar va pudratchilar qarzi" },
    { code: '6020', name: "Veksellar bo‘yicha qarz" },
    { code: '6110', name: "Ajratilgan bo‘linmalar va shu‘balar qarzi" },
    { code: '6120', name: "Ajratilgan bo‘linmalar va shu‘balar qarzi" },
    { code: '6230', name: "Kelgusi davr daromadlari" },
    { code: '6310', name: "Xaridorlardan olingan bo‘naklar" },
    { code: '6410', name: "Byudjet bilan hisob-kitoblar" },
    { code: '6510', name: "Sug‘urta va davlat maqsadli jamg‘armalari" },
    { code: '6520', name: "Sug‘urta va davlat maqsadli jamg‘armalari" },
    { code: '6610', name: "Ta’sischilarga dividendlar" },
    { code: '6620', name: "Ustav kapitaliga ulush berish" },
    { code: '6710', name: "Mehnat haqi to‘lovi" },
    { code: '6720', name: "Deponentlangan mehnat haqi" },
    { code: '6810', name: "Qisqa muddatli bank kreditlari" },
    { code: '6820', name: "Boshqa qisqa muddatli qarzlar" },
    { code: '6990', name: "Boshqa kreditorlar (nafaqalar, moddiy yordam)" },
    { code: '7810', name: "Uzoq muddatli kreditlar (xodimlarga)" },
    { code: '9010', name: "Tayyor mahsulot sotishdan tushum" },
    { code: '9020', name: "Tovarlar sotishdan tushum" },
    { code: '9030', name: "Xizmatlar va ishlar uchun tushum" },
    { code: '9210', name: "Asosiy vositalar sotishdan tushum" },
    { code: '9220', name: "Boshqa aktivlar sotishdan tushum" },
    { code: '9380', name: "Moliyaviy yordam (hadya, grant)" },
    { code: '9390', name: "Ortiqcha pul mablag‘lari (inventarizatsiya natijasi)" }
];

export const creditAccounts = [
    { code: '4010', name: "Xaridorlar va buyurtmachilar qarzi" },
    { code: '4110', name: "Shu‘ba va qaram korxonalar bilan hisob-kitoblar" },
    { code: '4120', name: "Shu‘ba va qaram korxonalar bilan hisob-kitoblar" },
    { code: '4220', name: "Xizmat safari uchun bo‘naklar" },
    { code: '4230', name: "Umumxo‘jalik xarajatlari uchun bo‘naklar" },
    { code: '4310', name: "Yetkazib beruvchilarga berilgan bo‘naklar" },
    { code: '4610', name: "Ta’sischilar qarzi (ustav kapitali)" },
    { code: '4710', name: "Xodimlar kreditga tovarlar uchun qarzi" },
    { code: '4720', name: "Xodimlarga berilgan ssudalar" },
    { code: '4730', name: "Aybdor shaxslardan kamomadlar va zararlar" },
    { code: '4790', name: "Mehnatga ortiqcha to‘langan summalar" },
    { code: '4810', name: "Moliyaviy ijara bo‘yicha qarzlar" },
    { code: '4830', name: "Boshqa korxonalardagi ulushdan daromadlar" },
    { code: '5010', name: "Milliy valutadagi pul mablag’lari" },
    { code: '5110', name: "Hisob-kitob schyoti (milliy valyutada)" },
    { code: '5210', name: "Valyuta hisob-kitob schyoti" },
    { code: '5530', name: "Bankdagi maxsus schyotlar" },
    { code: '5710', name: "Yo‘lda pul mablag‘lari (inkasso)" },
    { code: '5910', name: "Vaqtinchalik kamomadlar hisobi" },
    { code: '6010', name: "Yetkazib beruvchilar va pudratchilar qarzi" },
    { code: '6020', name: "Veksellar bo‘yicha qarz" },
    { code: '6110', name: "Ajratilgan bo‘linmalar va shu‘balar qarzi" },
    { code: '6120', name: "Ajratilgan bo‘linmalar va shu‘balar qarzi" },
    { code: '6230', name: "Kelgusi davr daromadlari" },
    { code: '6310', name: "Xaridorlardan olingan bo‘naklar" },
    { code: '6410', name: "Byudjet bilan hisob-kitoblar" },
    { code: '6510', name: "Sug‘urta va davlat maqsadli jamg‘armalari" },
    { code: '6520', name: "Sug‘urta va davlat maqsadli jamg‘armalari" },
    { code: '6610', name: "Ta’sischilarga dividendlar" },
    { code: '6620', name: "Ustav kapitaliga ulush berish" },
    { code: '6710', name: "Mehnat haqi to‘lovi" },
    { code: '6720', name: "Deponentlangan mehnat haqi" },
    { code: '6810', name: "Qisqa muddatli bank kreditlari" },
    { code: '6820', name: "Boshqa qisqa muddatli qarzlar" },
    { code: '6990', name: "Boshqa kreditorlar (nafaqalar, moddiy yordam)" },
    { code: '7810', name: "Uzoq muddatli kreditlar (xodimlarga)" },
    { code: '9010', name: "Tayyor mahsulot sotishdan tushum" },
    { code: '9020', name: "Tovarlar sotishdan tushum" },
    { code: '9030', name: "Xizmatlar va ishlar uchun tushum" },
    { code: '9210', name: "Asosiy vositalar sotishdan tushum" },
    { code: '9220', name: "Boshqa aktivlar sotishdan tushum" },
    { code: '9380', name: "Moliyaviy yordam (hadya, grant)" },
    { code: '9390', name: "Ortiqcha pul mablag‘lari (inventarizatsiya natijasi)" }
];
